inherit_from:
  - https://raw.githubusercontent.com/trailblazer/meta/master/rubocop.yml
  - .rubocop_todo.yml

Naming/MethodName:
  Exclude:
    - 'lib/trailblazer/transform/schema.rb'

Style/Lambda:
  EnforcedStyle: literal
